### ISSUE TITLE
Errors in example.bat

### ISSUE THREAD

**Issue by victor-homyakov** [dkandalov/code-history-mining-cli#2]
`example.bat` does not work exactly as its analog `example.sh`:

- it does not change directory to `junit` (`dir junit` just shows directory listing)
- it does not call `code-mining.bat visualize` because command interpreter does not return from the first call

Corrected `example.bat` should look somehow like that:

```bat
@echo off

git clone https://github.com/junit-team/junit
cd junit

call ..\code-mining.bat grab --from 01/01/2012 --to 01/01/2014
call ..\code-mining.bat visualize --csv junit.csv
```

**Comment by dkandalov** [comment]
Thank you! Updated.
